# -*- coding: utf-8 -*-
"""ejercicios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HbkyKJ9OvZ4chMux0QBbXfC2Xiwzrnag
"""

# Crear !Hola mundo¡
print("!Hola Mundo!")

a = ("!Hola mundo!")
b = ("!Hola Python!")
print("a", a)
print("b", b)

# Crear operaciones aritmeticas.
a = 12
b = 7

suma = a + b
resta = a - b
multiplicacion = a * b
división = a / b
porcentaje = a + b * 100 / a

print ("suma", suma)
print ("resta", resta)
print ("multiplicacion", multiplicacion)
print ("división", int(división))
print ("porcentaje", int(porcentaje))

# Especificar edad.

edad = 9

if edad >= 18:
    print("Es mayor de edad")
else:
    print("Es menor de edad")

# Crear contrseña con cantidad de intentos.
Contraseña_correcta = "Duppletch"
intentos_maximos = 4
intentos_actuales = 0

for intento in range(intentos_maximos):
    contraseña_ingresada = input("ingrese la contraseña: ")

    if contraseña_ingresada == Contraseña_correcta:
      print("!contraseña correcta¡ acceso concedido")
      break
    else:
      intentos_restantes = intentos_maximos - (intento + 1)
      print(f"contraseña incorrecta. Te quedan {intentos_restantes} intentos.")
else:
  print("Has agotado tus intentos. Acceso denegado.")

# Crear un Dado.

import random

def obtener_numero_aleatorio():
  return random.randint(1,7)

if __name__ == "__main__":
  numero = obtener_numero_aleatorio()
  print(f"El número aleatorio es:", numero)

# Crear Tabla de multilicación.

def obtener_numero():
  while True:
    try:
      numero = int(input("Ingrese un número:"))
      return numero
    except ValueError:
      print("Valor incorrecto. ingrese un número entero valido.")
def mostrar_tabla_multiplicar(numero):
  print(f"Tabla de multiplicar del {numero}:")
  for i in range(1, 15):
    resultado = numero * i
    print(f"{numero} x {i} = {resultado}")
def main():
  print("Bienvenido a la tabla de multiplicación")
  numero = obtener_numero()
  mostrar_tabla_multiplicar(numero)

if __name__ == "__main__":
  main()

# Guardar contactos.

# Juego de piedra, papel y tijera.

# Convrsión de temperaturas.

